# Generated by Django 3.0.8 on 2022-02-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20220212_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('In Progress', 'Inprogress'), ('Completed', 'Completed')], default='Scheduled', max_length=15),
        ),
    ]
